### PR TITLE
Fix for third criteria on apply page

### PR DESCRIPTION
**Pull request by aayushsanghavi**
#2401

### CODE REVIEW

**Comment by aayushsanghavi** [comment]
@gideonthomas is the patch fine? Could you please review it?

**Comment by gideonthomas** [comment]
Sorry. for the delay @aayushsanghavi!

@hannahkane does this look good?

**Comment by hannahkane** [comment]
Yes, looks great! +1

**Comment by gideonthomas** [comment]
Thanks @hannahkane

**Pull request merged**
