### PR TITLE
copy changes to gigabit

### LINKED ISSUE #2481: A couple more edits for the Gigabit Site
Hi, just a few more edits needed on the Gigabit Apply page (due to the introduction of Fluxx, the new grants management system that is set to go live on June 1):

Page: https://learning.mozilla.org/en-US/gigabit/apply/terms
1) We want to replace any use of 'Intent to Apply' with 'Letter of Intent'. There are two instances of this on the Terms & Conditions page, both in the first paragraph of the Submission Requirements section.

Page: https://learning.mozilla.org/en-US/gigabit/apply
1) We want to replace any use of 'Intent to Apply' with 'Letter of Intent'. There are three instances of this on this page, one in the Key Dates box and two in Step #2 in the application instructions section.
2) Remove the current version of #5 on the 'How to Apply' instructions (Register at mozilla.fluxx.io starting on June 1, 2017 and submit your application - including uploads of your timeline and budget - for review)
3) Add a new instruction after #2 that says "Successful Letter of Intent submissions will receive an invitation to submit a full application from our grant management system, Fluxx." (this addition should be a new #3)
4) Renumber the following instructions - (current #3 will become #4, current #4 will become #5)

### PR DESCRIPTION
**Pull request by hannahkane**
Fixes #2481 

**Changes proposed in this pull request:**
- minor copy changes to Terms and Apply pages

### CODE REVIEW

**Comment by jenntbeard** [comment]
Sorry, one more thing (putting in both places so it can get caught in this request). We need to add a #6 that says, “Successful submissions will receive an email invitation to submit a complete, final application to the Gigabit Community Fund on the Fluxx application system on or before Friday, July 15."

**Comment by hannahkane** [comment]
@jenntbeard - no problem, just added a commit to this PR. Hoping @gvn will have time to review and push to prod today.

**Comment by hannahkane** [comment]
Oh, @gvn's on PTO today. @mmmavis - could you take a look at this one, please?

**Comment by mmmavis** [comment]
@hannahkane can we push this on Monday since it's almost EOD Friday now?

**Comment by hannahkane** [comment]
@mmmavis - yes, let's do that

**Pull request merged**
