### PR TITLE
Some cleanup and QA

### PR DESCRIPTION
**Pull request by ScottDowne**
@alanmoo some fixes for the feedback I have gotten up to this point, and some generic cleanup. R?

### CODE REVIEW

**Comment by Pomax** [comment]
can you change the commit title so it reflects the work that was done? (we uses the commit title/message to build the changelog, "some cleanup and QA" doesn't say *what* got cleaned up and QA'd =)

**Comment by ScottDowne** [comment]
@Pomax updated.

**Comment by alanmoo** [comment]
This looks good, though there's still some work to go before this is ready when looking at it on mobile.

**Comment by ScottDowne** [comment]
@alanmoo yeah, I just took a quick look at mobile. Things I noticed that are unique to these pages:

The events page
- [ ] The "event resources" button nav button text doesn't fit.
- [ ] The hero unit image is totally off. Needs to be positioned better.

The events/resources page
- [ ] Hosting a Maker Party list text looks too big, needs some work.
- [ ] The Logos & Assets items look a little off. This wasn't something I built, so might not be new. Should be fixed anyway.
- [ ] Become a Maker Party partner section needs some centering.

And in general I feel like a lot of the headers are too big for mobile, but I wonder if that's all of l.m.o? and if it's intended?

**Pull request merged**
