### PR TITLE
[DO NOT MERGE] deploy test, branch to be discarded after feature branch deploy testing

### PR DESCRIPTION
**Pull request by Pomax**
testing.

### CODE REVIEW

**Comment by Pomax** [comment]
Build breaking heavily. Bisecting between current head and August 2nd.

**Comment by Pomax** [comment]
august 2nd is good.

**Comment by Pomax** [comment]
midpoint 43d1b3f is good, but has a test-react-warnings task that takes 40 seconds.

**Comment by Pomax** [comment]
7c58fd9 is technically good, locally, but has a `test-react-warnings` task that takes 40 seconds to run.

**Comment by Pomax** [comment]
b52f9fa is technically good, locally, but has a test-react-warnings task that takes 40 seconds to run.

**Comment by Pomax** [comment]
24fdd9f is good, locally, but has an >1min `test-react-warnings` task

**Comment by Pomax** [comment]
c96476a is good, locally, but has a 1m50 `test-react-warnings` task and very long timeout on the app smoketests.

**Comment by Pomax** [comment]
2a84424  is good, locally, but has a 1m50 test-react-warnings task and very long timeout on the app smoketests.

**Comment by Pomax** [comment]
da59ca4  is good, locally, but has a 1m50 test-react-warnings task and very long timeout on the app smoketests.

**Comment by Pomax** [comment]
ffdd0aa is good, locally, but has a 1m50 test-react-warnings task and very long timeout on the app smoketests.

**Comment by Pomax** [comment]
Locally, at initial test:
```
2d770b43eeb405a9cf6c5b6e7fec5a5aa557394a is the first bad commit
commit 2d770b43eeb405a9cf6c5b6e7fec5a5aa557394a
Author: Pomax <pomax@nihongoresources.com>
Date:   Mon Aug 22 16:11:13 2016 -0700

    test timeout rollbacks

:040000 040000 65995e8a82caad6e8005006a42baf946719bc218 0e4d8c9292242a4d1f4d00a5a17a978a8b4ab8f6 M      pages
:040000 040000 7dc35bf41adda7baaa874280528b44fa05d0bcac 4f2e7a22500eef200d37583c1be2b53eb6b9e778 M  test
```

**Comment by Pomax** [comment]
One thing revealed during process.stdout writing is that the reason our app.js test takes so incredibly long is that it literally tests all links exposed by the router: if we have 10 locales, that's every URL routes.jsx generates, times ten, because `en-US` is a different set from `sv-SE` which is a different set from etc. 

/cc @alanmoo

**Comment by alanmoo** [comment]
Yeah, that's what I was starting to address in #2108, but realized that alone wouldn't solve our problems.

**Comment by Pomax** [comment]
Ah, had not seen that issue. We might have to address some of it first, in order to get the code back to at least "compiling" in CI... or roll back master, which I really hope we don't end up having to do.

**Comment by alanmoo** [comment]
I did a git bisect and it was weird- it pointed at f557e05a7f91fd53a5a1a50f87e01a1820386061 being the bad commit, but #2102 passed testing

**Comment by Pomax** [comment]
... tests pass O_O @alanmoo 

passing commit binds the indexStatic timeout we use in the tests to the actual indexStatic generator itself, and then we use that both in the "index static test" and "app test" in the tests that rebuild the index.

**Comment by Pomax** [comment]
still deploy errors based on pontoon, though:
```
> learning.mozilla.org@1.0.5 l10n /tmp/build_3f18d5d3cd863446cfba23e1e11be412/mozilla-learning.mozilla.org-a56724c
       > pontoon-to-json
       
       processing the following locales: ['en-US']
       [TypeError: locales.map is not a function]
       module.js:327
       throw err;
```

**Comment by Pomax** [comment]
`console.log(process.env)` after a habitat load shows:
```
SUPPORTED_LOCALES: '['en-US']',
```
which is definitely not an array

**Comment by Pomax** [comment]
```
> learning.mozilla.org@1.0.5 l10n /tmp/build_e97904cf3bb69b9f6531a20f7e9ae803/mozilla-learning.mozilla.org-97c8b2f
       > node pontoon-test.js
       
       process.env: ['en-US'] : string
       habitat env: ['en-US'] : string
       processing the following locales: ['en-US']
       constructor: function String() { [native code] }
       [TypeError: locales.map is not a function]
       module.js:327
       throw err;
```

So much wrongness....

**Comment by Pomax** [comment]
Sooooo it looks like habitat is not doing what we expect it to do, in combination with heroku.

On Heroku, we set the `SUPPORTED_LOCALE` variable to `['en-US']`, which you'd think is right, but habitat ends up loading it as the *String* `"['en-US']"`, so the way I'm getting this to work is to check for that in the pontoon-to-json code and do a manual `JSON.parse` pass if I see `[` in the locale string:

```
var habitat = require('habitat');
habitat.load();
var env = new habitat();

var supportedLocales = process.env.SUPPORTED_LOCALES || `*`;

if (supportedLocales.indexOf('[') !== -1) {
  // FIXME: TODO: this circumvents a problem with habitat and
  //              heroku, where the environment variable ['en-US']
  //              magically becomes '['en-US']', which thus gets
  //              turned into a String, rather than an Array...
  //
  // see: https://github.com/mozilla/learning.mozilla.org/pull/2120
  //
  supportedLocales = JSON.parse(supportedLocales.replace(/'/g,'"'));
}
```

**Comment by Pomax** [comment]
the fixes from this exploratory issue have been landed in the appropriate places. closing

**Pull request closed without merging**
