### PR TITLE
fix: Remove reference to Open News fellowship

### LINKED ISSUE #2463: Remove reference to Open News fellowship
...on [this page](https://learning.mozilla.org/en-US/opportunities)

The Become a Fellow section should include this sentence: Apply to join the next cohort of Science, Advocacy, and Developer Network Fellowships that best matches your interests and skills [remove "News"]

### PR DESCRIPTION
**Pull request by aayushsanghavi**
- [ ] Localization addressed

Fixes #2463 

**Changes proposed in this pull request:**
- Removed reference to Open News fellowship from the opportunities page

This is how it looks (marked in the black border)- 

screenshot from 2017-04-18 08-39-04

### CODE REVIEW

**Comment by aayushsanghavi** [comment]
@mmmavis I've currently removed the newsLink variable from the en-US locale only but there are many other locales which still have the newsLink variable. We'd have to remove it from all those files too right?

**Comment by mmmavis** [comment]
@gideonthomas ⬆️ 😉

**Comment by mmmavis** [comment]
hey @aayushsanghavi I wasn't involved in setting up the localization system on the Learning site that's why I pinged @gideonthomas here for help. From what he told me yesterday - we only need to update `en-US` since for other locales we are pulling strings directly from Pontoon. @gideonthomas also mentioned "the recommendation for changes to strings is that you create a new key-value pair with the new string and use that key in your code instead". Does that make sense? ( @gideonthomas correct me if I explained anything wrong 😁 )

**Comment by gideonthomas** [comment]
@mmmavis sorry, I totally forgot to reply here. But yeah, you got it spot on!

**Comment by aayushsanghavi** [comment]
@gideonthomas could you elaborate on "create a new key-value pair with the new string and use that key in your code instead". I didn't understand that.

**Comment by aayushsanghavi** [comment]
I made a new string and I'm using that instead of the previous message string. @gideonthomas please take a look and let me know if its fine.

**Comment by gideonthomas** [comment]
awesome! Thanks @aayushsanghavi!

**Pull request merged**
