### PR TITLE
login emulation the teach-api connector

### LINKED ISSUE #2017: add login emulation to teach-api.js
technically already implemented in the clubform branch, but this should be landed separaterly really.

### PR DESCRIPTION
**Pull request by Pomax**
fixes #2017

### CODE REVIEW

**Comment by alanmoo** [comment]
What am I looking for when testing this? I change the .env variables but see no change on the homepage of the learning site.

**Comment by alanmoo** [comment]
^ @Pomax

**Comment by Pomax** [comment]
@alanmoo with this branch checked out, create an `.env` file and set the login emulation values as indicated in the README.md, then without a teach-api or id etc running see if the site's sign in button logs in you, and sign out signs you out, without any errors around "there is no teach-api halp halp".

**Comment by alanmoo** [comment]
I'm just constantly getting `Unable to contact login server.
Refresh the page to try again.` in the sign-in area.

Current .env:
````
ENABLE_BADGES="yes please, that would be great"
LOGIN_EMULATION=0
````

**Comment by Pomax** [comment]
I've updated the PR - turns out I had forgotten to add the new environment variables to the Webpack config, so they only worked on the server, not on the client after bundling. Yay! Want to re-review?

**Comment by alanmoo** [comment]
If `LOGIN_EMULATION` is on and `LOGIN_EMULATION_LOGGEDIN` is off, I'm not sure I understand the difference in what's happening- the "sign in" link directs to the same spot regardless of `LOGIN_EMULATION`. (the state query param is different but I'm not clear on what that is).

@Pomax can you explain?

**Comment by Pomax** [comment]
With login emulated I needed a way to be both logged in or logged out, without hitting the teach-api, but I think in this case the default should be "logged in" unless explicitly logged out. Let me reverse that var (and its name)

**Comment by alanmoo** [comment]
But with login emulated you can't change state from the front end, right?

**Comment by Pomax** [comment]
no, but you can determine the login state without needing to hit the teach-api for dev purposes, so you can bootstrap a logged in or logged out state, and then `npm start`, without most of the code not running because the teach-api connector crashes out.

I could probably rewrite this so the sign in/out buttons work more like a mocked teach-api so you can click sign in and sign out rather than needing to bootstrap

**Comment by alanmoo** [comment]
👍

**Pull request merged**
