### PR TITLE
adds MozFest MCW info

### LINKED ISSUE #2358: Update Mozilla Curriculum Workshop Landing Page for MozFest
The Curriculum Workshop landing page needs to be updated to reflect the upcoming "Live from MozFest" broadcast:

**"Upcoming Workshop" blue call out box:**
 October 30th - 6am PT/ 9am ET/ 2pm BST/ 1pm UTC

@chadsansing - can confirm the times are correct above?

**Paragraph beneath callout box:**
Join co-hosts Amira Dhalla and Chad Sansing live from London as they talk with guests from around the world about all the learning and making going on at at the festival. Members of the Mozilla Clubs network will appear on the webcast, as well, to share their MozFest experiences throughout the network.

**For reference:** Air Mo landing page: https://air.mozilla.org/mozilla-curriculum-workshop-live-from-mozfest-2016-10-30 

Waiting on embed code from Air Mo team.

### PR DESCRIPTION
**Pull request by hannahkane**
- [X] Localization addressed - NA

Fixes #2358 

**Changes proposed in this pull request:**
- updates Mozilla Curriculum Workshop landing page with details about Oct 30th call, and provides link to...
...new archive page for Oct 11th workshop

@gvn or @flukeout - are either of you available to review this?

### CODE REVIEW

**Comment by hannahkane** [comment]
hmmm...tests pass locally. Could this be a timeout thing? Anyone know?

**Comment by gvn** [comment]
I forced the test to re-run and it passed, so must have been a timeout!

**Comment by hannahkane** [comment]
thanks, @gvn - any chance you could push this to production today or tomorrow?

**Comment by gvn** [comment]
Yeah, have you verified it on staging?

**Comment by hannahkane** [comment]
@gvn - yep, looks good on staging.

**Comment by KGorr** [comment]
Sorry to stick my head in here but we just realized that the time changes in London on Sunday morning, which means the time on the landing page needs to be "7am PT/10am ET/2pm UTC". Can this adjustment be made before the page updates goes live, please? Sorry for the inconvenience! @gvn @hannahkane

**Comment by gvn** [comment]
@KGorr @hannahkane This should be fixed and live on production!

**Comment by hannahkane** [comment]
yay! thanks.

**Comment by KGorr** [comment]
Woo - thanks! One thing that we need to double check: The time on the page left 2pm BST remaining, but London switches to GMT, which is the same as UTC. I think 2pm BST should be removed to be 100% accurate. Feel free to fact check me on this ;) @gvn

**Pull request merged**
