### PR TITLE
adds new gigabit events

### LINKED ISSUE #2493: Adding new items to the Gigabit Events Page
Need to add several upcoming events to the Gigabit Events page - https://learning.mozilla.org/en-US/gigabit/events

We have five events that are ready to be added to the page mentioned above, highlighted in yellow in this Google Sheet - https://docs.google.com/spreadsheets/d/1X3nmzwZkG0lJh-VfzBhuN6SQws2VM6WeR8Rybol8GTk/edit#gid=0. A link to the event and a link to an image is provided for each. We have a sixth event that we are waiting on details for. Should it be confirmed in time, I will update the sheet, or submit another bug when it is available. 

If possible, can the date following the last date of the event be marked as the day to remove from the site? Thanks! [As always, if there is a way for me to manually update, let me know! :)]

### PR DESCRIPTION
**Pull request by hannahkane**
Fixes #2493

**Changes proposed in this pull request:**
- adds five new events to the Gigabit Events page

### CODE REVIEW

**Comment by hannahkane** [comment]
@gvn - could you please review this and, assuming all is OK, push it to prod next week? Thanks!

**Comment by jenntbeard** [comment]
Not sure the status of this request but two of the events have now past (today and yesterday). I have also just added a new event to the grid for July 20 - https://docs.google.com/spreadsheets/d/1X3nmzwZkG0lJh-VfzBhuN6SQws2VM6WeR8Rybol8GTk/edit#gid=0.

**Comment by gvn** [comment]
It has been merged, so I'd recommend making a new ticket to add/remove any other events.

**Comment by jenntbeard** [comment]
Okay, thanks.

**Pull request merged**
