### PR TITLE
Replaced promo banner with MozFest promo & few styling adjustments

### LINKED ISSUE #1924: Implement homepage promotion banner: MozFest call for proposals
Replace the ENCRYPT banner on the homepage with a banner promoting the MozFest call for proposals. 
screen shot 2016-07-07 at 3 37 35 pm

See redpen: https://redpen.io/zcd9175df07bdc2b9e

**Copy:** The world's leading event to build, debate, and explore the future of our lives online. 
**Copy CTA:** Learn more
**CTA Link:** https://mozillafestival.org/proposals
**MozFest wordmark:** https://drive.google.com/a/mozillafoundation.org/folderview?id=0B4Q8pzCpDS_eelFIZWxzb05CdlU&usp=drive_web&ddrp=1#
**Background Colour:** #f1f1f2 (unified light grey)

Based on copy and design updates from #1892

### PR DESCRIPTION
**Pull request by mmmavis**
Fixes #1924

**Changes proposed in this pull request:**
- Replaced promo banner with MozFest promo
- few styling tweaks including changing background colour of the quotes section, fixing alignment of the 3 icon button on hero banner

### CODE REVIEW

**Comment by cadecairos** [comment]
Looks good! tested in responsive design mode in Firefox and Chrome, all looks well.

**Comment by mmmavis** [comment]
🎉

**Comment by mmmavis** [comment]
@hannahkane anyone I should tag to get this live? or I should do it myself?

**Comment by cadecairos** [comment]
It'll go out to teach.mofostaging.net automatically once you merge. 

Once we're okay with it on staging, we can deploy it with a merge to the master branch.

**Comment by mmmavis** [comment]
cool, let me hit the merge buttonnnn now

**Pull request merged**
