### PR TITLE
[PUSH LIVE ON APRIL 2] Added more gigabit projects & fixed/removed broken logos

### PR DESCRIPTION
**Pull request by mmmavis**
## TO BE MERGED AND PUSHED LIVE ON APRIL 2

Related to #2552

### CODE REVIEW

**Comment by alanmoo** [comment]
cc @jenntbeard

**Comment by jenntbeard** [comment]
Awesome! Just to confirm, this will be pushed live on Monday, April 2? Thank you for getting to this so quickly!!

**Comment by mmmavis** [comment]
@jenntbeard yup yup I've set a reminder for it! We'll push it live on Monday.

**Comment by jenntbeard** [comment]
Fantastic, thank you so much @mmmavis !

**Comment by alanmoo** [comment]
Merging this now so we can check it out on staging and deploy Monday

**Pull request merged**
