### PR TITLE
adds Intermediate Web Lit II module

### LINKED ISSUE #1853: Build page for Intermediate Web Literacy II: Storytelling with Scripts
Content is here: https://docs.google.com/document/d/1oNXBYCgZw0AJbiK_FGYTDRVpqMBz0UiPi0yCCYbYdSc/edit?ts=572a1fe8

### PR DESCRIPTION
**Pull request by hannahkane**
Fixes #1853

**Changes proposed in this pull request:**
- adds new page for Intermediate Web Lit II module
- updates /activities to reflect new module

### CODE REVIEW

**Comment by hannahkane** [comment]
@mmmavis - R?

**Comment by hannahkane** [comment]
@mmmavis - possible for you to review this and push it to production before you go on PTO?

**Comment by mmmavis** [comment]
yup yup

**Comment by mmmavis** [comment]
R+ Thanks for being so awesome @hannahkane 👯

**Pull request merged**
