### PR TITLE
Corrected Club Captain name spelling & country

### LINKED ISSUE #2130: Club Captain Testimonial Fixes
From an email by @amirad...

* [x] Update location for first two club captain testimonials to "South Africa"
* [x] Fix spelling of first club captain's name, it's "Asisipho"

### PR DESCRIPTION
**Pull request by flukeout**
**Changes**
* Changed "Africa" to "South Africa" for two Club Captains
* Changed "Isisipho" to "Asisipho" in the copy and localization variable names

Changes will be reflected on ``/clubs/start`` page.

Fixes #2130

### CODE REVIEW

**Comment by flukeout** [comment]
@alicoding Since it's localization related, can you review please?

**Comment by Pomax** [comment]
looks like this needs a rebase before we can land it.

**Comment by flukeout** [comment]
@Pomax rebased

**Comment by alicoding** [comment]
👏

**Pull request merged**
