### PR TITLE
adds new activities to web lit map

### LINKED ISSUE #2095: Add new activities to Web Lit Map
Since we published the Web Literacy Map, we've added lots of new activities. The map should be updated to reflect the new activities.

@alicoding - I'm pretty sure I can do this myself. Wondering if it would be disruptive if I do this now? Would you prefer this happens after the migration to the new model?

### PR DESCRIPTION
**Pull request by hannahkane**
Fixes #2095

Localization - NA

**Changes proposed in this pull request:**
- adds 24 new activities and maps them to skills on the web lit map
- updates several activities skills to align with how the activities are presented on the /activities page

### CODE REVIEW

**Comment by hannahkane** [comment]
not sure who is the best person to review this. @ScottDowne? @alicoding? @alanmoo?

**Comment by hannahkane** [comment]
hmm...I'm going to need some help resolving the failures. Tests passed locally.

**Comment by alanmoo** [comment]
I don't think it's your code, testing is jacked in the repo at the moment.

**Comment by hannahkane** [comment]
@alanmoo or @Pomax - can you please advise about what I should do to fix this? Thank you!

**Comment by alanmoo** [comment]
Rebase from master and then force-push back up should do the trick. (Unless github has a way to do this which I'm not aware of)

**Comment by alicoding** [comment]
I just rebuild travis build again...

**Comment by alanmoo** [comment]
Oh derp. That works too.

**Comment by alicoding** [comment]
yay green light!

**Comment by hannahkane** [comment]
Yay! 

Probably still need someone to review this code, though. Anyone available?

**Comment by alicoding** [comment]
@hannahkane I reviewed your code, but not sure if I'm suppose to do anything else? I mean no syntax error, no typo that I can find and travis is passing.

**Comment by hannahkane** [comment]
Oh, thanks, @alicoding. I didn't realize you'd looked at it; thought you were just responding to Travis's green light. Merging now.

**Pull request merged**
