### PR TITLE
Add mozmaker css files

### PR DESCRIPTION
**Pull request by alicoding**

### CODE REVIEW

**Comment by alicoding** [comment]
@gideonthomas R?

**Comment by alanmoo** [comment]
Shouldn't we not be pulling in bootstrap then? And why is this from the web, not local?

**Comment by alicoding** [comment]
@alanmoo bootstrap is there, and this is going to be just for testing until we work on `mozmaker`/`onesie` to make it compile all the css needed for this.

**Comment by alanmoo** [comment]
I know bootstrap is there, but mozilla.github.io/mozmaker/dest/css/mozmaker.css looks to be a superset of bootstrap. So aren't we pulling in duplicate CSS?

**Comment by mmmavis** [comment]
Question - Are we ready to pull in `mozmaker.css`? It will overwrite lots of existing stylings on the site.

cc @sabrinang @Pomax

**Comment by mmmavis** [comment]
and cc @kristinashu

**Comment by alanmoo** [comment]
Agreed, I'm not sure it's the right approach to globally pull it in. I'm thinking we put the `<link>` tag in the component that wraps wordpress content.

**Comment by Pomax** [comment]
putting the link in sounds fine to me - even if we loaded multiple snips, we'd just be linking to the same stylesheet several times, right? (caching will make that a nonissue)

**Comment by alicoding** [comment]
@alanmoo @mmmavis our bigger problem of all this is that this repo uses bootstrap v3 and onesie (mozmaker) is using bootstrap v4... @Pomax

**Comment by Pomax** [comment]
hm, do we have a list of the concrete issues that results in?

**Comment by alicoding** [comment]
Let's close this until we have re-write this site with mofo-bootstrap implemented.

**Pull request closed without merging**
