### PR TITLE
Fix Safari bug, change 301 to 307 redirect

### LINKED ISSUE #2005: Locale negotiation fails on Safari
On staging server, locale negotiation fails on Safari and results in an endless redirect.

### PR DESCRIPTION
**Pull request by alanmoo**
Fixes #2005

**Changes proposed in this pull request:**
- Change 301 permanent redirect to 307 temporary (solves debugging issues, really shouldn't be permanent because a user may want to change locale)
- Bump mofo-localizr so that lowercase regions in "accept-language" header don't fail

### CODE REVIEW

**Comment by alicoding** [comment]
R+ but please file an issue to fix that weird redirect for hitting `/en-us` and will redirect them to `/en-US/en-us`

**Comment by alanmoo** [comment]
@ali I'm not sure what issue you're talking about- this should have solved that with the update to mofo-localizr.

**Comment by ali** [comment]
@alanmoo Just heads up seems like y'all are getting me mixed up with @alicoding:

2016-07-28 at 5 18 pm

Those @ mentions are probably more useful to them than they are to me ;)

**Comment by alanmoo** [comment]
Oops! Apologies, though I'm sure it'll happen again- just ask @cade ;)

On Thu, Jul 28, 2016 at 5:20 PM Ali Ukani

<
mailto:Ali Ukani <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

https://github.com/alanmoo
Just heads up seems like y'all are getting me mixed up with
https://github.com/alicoding
:

https://cloud.githubusercontent.com/assets/515861/17229826/5def0ffc-54e7-11e6-8ee6-9a5539f05d32.png

Those @ mentions are probably more useful to them than they are to me ;)

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/mozilla/learning.mozilla.org/pull/2011#issuecomment-236028799
, or

**Comment by cade** [comment]
Sometimes I feel like an honorary member of the Mozilla team. But with no responsibilities.

It's nice. 😁

**Pull request merged**
