### PR TITLE
adds AirMo embeds to comm call/MCW landing pages

### LINKED ISSUE #2310: add AirMo embeds to MCW and Comm Call landing pages
`<iframe src="https://air.mozilla.org/mozilla-learning-science-community-call-2016-10-13/video/" width="896" height="524" frameborder="0" allowfullscreen></iframe>`

`<iframe src="https://air.mozilla.org/mozilla-curriculum-workshop-ada-lovelace-day-2016-10-11/video/" width="896" height="524" frameborder="0" allowfullscreen></iframe>`

### PR DESCRIPTION
**Pull request by hannahkane**
- [x] Localization addressed - NA

Fixes #2310

**Changes proposed in this pull request:**
- embeds AirMozilla livestream to Community Call and Curriculum Workshop landing pages
- adds instructions to user to refresh browser, as per note from Richard Milewski

### CODE REVIEW

**Comment by hannahkane** [comment]
@flukeout - wondering if you can take a look at this. This month we're switching from YouTube livestreams to AirMozilla for Community Calls and Curriculum Workshops. When I look at this on my local machine, the video section just appears like a big grey box.

From Richard: "The limitation I was hoping to work around is that up until 10 minutes before the event, that iframe will only display a very small link that says "Watch on Air Mozilla".  Once the stream is up it will display the video, but switching from the no-stream mode to the video mode will require a page refresh in the browser."

I'm confused because I don't see the "Watch on Air Mozilla" link, so I'm wondering if I've done something wrong.

**Comment by hannahkane** [comment]
@flukeout is out of office, and these changes are urgent. @gvn - would you have time to review this PR?

**Comment by gvn** [comment]
So, codewise this looks good, but I think we need an updated Content Security Policy for Airmo that allows `learning.mozilla.org` to embed it as an iframe.

**Comment by hannahkane** [comment]
Closing because this is broken.

**Comment by gvn** [comment]
I didn't realize we have a CSP for LMO, so I can try tweaking it to add AirMo:

https://github.com/mozilla/learning.mozilla.org/blob/master/server/security-headers.js

**Pull request closed without merging**
